// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rlj4CvEOeYUpQzb2GRWk_YAEHpQKafA',
    appId: '1:230123887200:web:a785a2085fe568c9d00105',
    messagingSenderId: '230123887200',
    projectId: 'restoration-c3993',
    authDomain: 'restoration-c3993.firebaseapp.com',
    storageBucket: 'restoration-c3993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjur0okv5SunWIn5ppmmEQmz3PDDW1PDY',
    appId: '1:230123887200:android:bc2e25684fee4a49d00105',
    messagingSenderId: '230123887200',
    projectId: 'restoration-c3993',
    storageBucket: 'restoration-c3993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHw5FjsVblQnXc6IfjF5Eu-dAq0hvel0',
    appId: '1:230123887200:ios:76ce1c08f5aff975d00105',
    messagingSenderId: '230123887200',
    projectId: 'restoration-c3993',
    storageBucket: 'restoration-c3993.appspot.com',
    iosClientId: '230123887200-5ocnfrjqdrbdkfi5d5nt80ml75kgp0f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.royalRestoration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHw5FjsVblQnXc6IfjF5Eu-dAq0hvel0',
    appId: '1:230123887200:ios:e35bdcdcf58188d2d00105',
    messagingSenderId: '230123887200',
    projectId: 'restoration-c3993',
    storageBucket: 'restoration-c3993.appspot.com',
    iosClientId: '230123887200-58nk2sctohk0qldd3bpe1f9mfc1i0kod.apps.googleusercontent.com',
    iosBundleId: 'com.example.royalRestoration.RunnerTests',
  );
}
